// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhSFZwEkrxsKvv78Layk4iyEkotrEcQ_Q',
    appId: '1:801688103491:web:858adf9e4c90b66cd202f6',
    messagingSenderId: '801688103491',
    projectId: 'tugas-app-pernikahan',
    authDomain: 'tugas-app-pernikahan.firebaseapp.com',
    storageBucket: 'tugas-app-pernikahan.firebasestorage.app',
    measurementId: 'G-95T8VRYMJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAonh03_vp7U_fDqeSdQ6usGrKARUA7bdI',
    appId: '1:801688103491:android:c853c04047715cd3d202f6',
    messagingSenderId: '801688103491',
    projectId: 'tugas-app-pernikahan',
    storageBucket: 'tugas-app-pernikahan.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhSFZwEkrxsKvv78Layk4iyEkotrEcQ_Q',
    appId: '1:801688103491:web:676ab66116d8e0b6d202f6',
    messagingSenderId: '801688103491',
    projectId: 'tugas-app-pernikahan',
    authDomain: 'tugas-app-pernikahan.firebaseapp.com',
    storageBucket: 'tugas-app-pernikahan.firebasestorage.app',
    measurementId: 'G-11FZGGTXJL',
  );
}
